### ISSUE TITLE
Turn on/off hovers / symref highlighting etc-

### ISSUE THREAD

**Issue by Jazzpirate** [KWARC/FLAMS#36]
"no distraction"-mode, maybe configurable what exactly that means, maybe less invasive color options?

**Comment by Jazzpirate** [comment]
Silas:
"More blur on the bold font feels better."
```css
.ftml-comp {
    text-shadow: .1ex .1ex .3ex #1e90ff80;
}
.ftml-def-comp {
    text-shadow: .1ex .1ex  .5ex #c7158580;
    font-weight: bold;
}
```
